package com.bloemer.api.introducaoaclases.interfaces.clases;

public interface Tributavel {
    //posso escrever assim um atributo...
    //public static final double IMPOSTO =0.2;  ou assim...
    double IMPOSTO = 0.2;
    // todos os metodos são abstratos,entao posso escrever assim...
    //public abstract void... ou assim...
    void calcularImposto();
}
